# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: tag
  value: '$(Build.BuildId)'
- name: namespace
  value: 'akhinat1-in'
- name: sourceimage
  value: 'dotnet:2.1'
- name: applicationname
  value: 'stacksmith'
- name: buildConfiguration
  value: 'Release'
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImageName: $(vmImageName)
    steps:
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'My Openshift'
        cmd: 'oc new-build --name=$(applicationname) --image-stream=$(sourceimage) --strategy=source --binary  -n $(namespace)'
        uselocalOc: true
        ignoreFlag: true
      displayName: Creating New Build
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'My Openshift'
        cmd: 'start-build $(applicationname) --from-dir=/home/vsts/work/1/s/ --follow -n $(namespace)'
        uselocalOc: true
        ignoreFlag: true
      displayName: Starting Build

